### PR TITLE
1.0 pkg config mysql client

### PR DESCRIPTION
**Pull request by grooverdan**
Was using a mysql-5.7 build which didn't contain mysqlclient_r library so I assume it renamed.

also add PKG_CONFIG to detect libraries.

### CODE REVIEW

**Comment by utdrmac** [comment]
```
git clone https://github.com/akopytov/sysbench
cd sysbench
git fetch origin pull/39/head:pull39
git checkout pull39
./autogen.sh
root@localhost:/usr/src/sysbench# ./autogen.sh
./autogen.sh: running `aclocal -I m4'
./autogen.sh: running `libtoolize --copy --force'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
./autogen.sh: running `autoheader'
./autogen.sh: running `automake -c --foreign --add-missing'
configure.ac:27: installing 'config/ar-lib'
configure.ac:21: installing 'config/compile'
configure.ac:11: installing 'config/config.guess'
configure.ac:11: installing 'config/config.sub'
configure.ac:16: installing 'config/install-sh'
configure.ac:16: installing 'config/missing'
sysbench/Makefile.am: installing 'config/depcomp'
./autogen.sh: running `autoconf'
configure.ac:35: error: possibly undefined macro: AC_MSG_CHECKING
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:45: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:52: error: possibly undefined macro: AC_ARG_WITH
configure.ac:101: error: possibly undefined macro: AC_CACHE_CHECK
configure.ac:175: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:268: error: possibly undefined macro: AC_MSG_ERROR
configure:14447: error: possibly undefined macro: dnl
configure:14473: error: possibly undefined macro: AC_HELP_STRING
configure:14515: error: possibly undefined macro: AC_PATH_PROG
Can't execute autoconf
```

**Comment by grooverdan** [comment]
@utdrmac , interesting, what OS/version of autoconf do you have? Seemed to pass the travis test ok. I'm using a Fedora23 based distro here.

**Comment by utdrmac** [comment]
```
root@localhost:~# uname -a
Linux localhost.localdomain 3.10.65-5-pine64-longsleep #19 SMP PREEMPT Fri Apr 15 19:55:17 CEST 2016 aarch64 aarch64 aarch64 GNU/Linux

root@localhost:~# autoconf -V
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
root@localhost:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

**Comment by grooverdan** [comment]
@utdrmac I tested it on a docker image. The error goes away after installing pkg-config.

**Comment by utdrmac** [comment]
the _r libraries were completely/officially removed in 5.7 so if you want to patch this up, it no longer needs to check for anything _r if running 5.7+

**Comment by akopytov** [comment]
I'd be happy to merge this, if not another external dependency on pkg-config, and obscure messages thrown by autoconf when it's not installed. I added pkg-config to the luajit branch, but then learned about this issue the hard way.

I'll look for other possible ways and merge this one if I won't find any.

**Comment by grooverdan** [comment]
The pkg-config package provides the m4 macros which is needed to the generation of the configure script only. Even a source distro that provided the configure shouldn't need pkg-config installed. Thanks for your consideration.

**Comment by akopytov** [comment]
@grooverdan, I tried to fix this without resorting to pkg-config in https://github.com/akopytov/sysbench/commit/8ac5bd67208b2297a086eef4ee8c0c41c0ed1af4. Please let me know if it doesn't work for you.

**Pull request closed without merging**
