### PR TITLE
travis: test ppc64le

### LINKED ISSUE #129: support for powerpc architecture
I tried to build it on my machine which is powerpc 64 bit little endian. I have ubuntu 16.04 OS.
I got the following error-  #error "No support for PowerPC 64 bit mode". I also tried with replacing the luajit lib folder with downloading the current one from github, but i am not succesful to build it. Is some extra steps required to build it on power pc architecture or is it missing the feature for powerpc

### PR DESCRIPTION
**Pull request by grooverdan**
partial support for automated testing.

The jit error seems expected as per #129.

closes #129

### CODE REVIEW

**Comment by akopytov** [comment]
Thanks. I tried fixing `opt_luajit_cmd.t`, but Travis builds on ppc64le now fail for me like this: https://travis-ci.org/akopytov/sysbench/jobs/397027255

Not sure if that's a problem with `.travis.yml` or ppc64le travis image, or something else.

**Comment by grooverdan** [comment]
Its the ppc64le travis image that doesn't have the same documented mysql/postgresql default user names as the x86_64 image. And the folks have changed the image so my workarounds don't work any more. Leave it with me, I'll take it up with the maintainers of the ppc64le image.

**Comment by grooverdan** [comment]
And the definition of TRAVIS_OS_NAME changed - https://github.com/travis-ci/travis-build/commit/4e909a4a84b676cc603f1b030efcf9536ded2bf1, glad I hadn't used it too much. probably better overall.

**Comment by grooverdan** [comment]
reminder - this is ready

**Comment by akopytov** [comment]
@grooverdan Sorry for the delay in responding to this. I just merged the ppc64le LuaJIT port to sysbench, so there's no need to fiddle with `rm -rf; git clone ...`. I also merged your latest changes from this PR, but the resulting branch is still failing in Travis in the same way as before: https://travis-ci.org/akopytov/sysbench/jobs/418873313

 Any ideas?

**Comment by grooverdan** [comment]
https://travis-ci.org/akopytov/sysbench/jobs/418873313#L432 lists the fail to start.

I was running a bunch of tests 1-2 months back: https://github.com/grooverdan/travis-test

I've just retriggered the job as there where a few travis-build/image fixes - https://travis-ci.org/grooverdan/travis-test

I'm having a little trouble seeing the differences at the moment. I think there was something about forcing to a VM environment (despite sudo: false) if it sees sudo in the yaml file.

A mariadb addon might be the quick way out.

**Comment by grooverdan** [comment]
postgresql off topic but you might find useful:

I did some experiments with postgres travis if you want to try multiple versions: https://travis-ci.org/getpatchwork/patchwork/builds/418771098

some oddities between versions exists https://travis-ci.org/getpatchwork/patchwork/builds/418771098

**Comment by akopytov** [comment]
@grooverdan hm, I see it fails in the same way: https://travis-ci.org/grooverdan/travis-test/jobs/419045724#L360

**Comment by grooverdan** [comment]
Ok. I'm still looking at how to get travis having a started MySQL and Postgresql database on POWER. Will get back to you.

I tested locally on a P8 on your travis_ppc64le branch which quickly runs into LUA errors. How did you go about the merge of third_party/luajit?
<pre>
===============================================================================
sysbench version   : 1.1.0-3406028
CC                 : gcc
CFLAGS             : -O3 -funroll-loops -ggdb3  -mcpu=power8 -Wall -Wextra -Wpointer-arith -Wbad-function-cast -Wstrict-prototypes -Wnested-externs -Wno-format-zero-length -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wcast-align   -pthread
CPPFLAGS           : -D_GNU_SOURCE  -DCK_MD_CACHELINE=128  -I$(top_srcdir)/src -I$(abs_top_builddir)/third_party/luajit/inc -I$(abs_top_builddir)/third_party/concurrency_kit/include
LDFLAGS            :  
LIBS               : -laio -lm 

prefix             : /usr/local
bindir             : ${prefix}/bin
libexecdir         : ${prefix}/libexec
mandir             : ${prefix}/share/man
datadir            : ${prefix}/share

MySQL support      : yes
PostgreSQL support : no

LuaJIT             : bundled
LUAJIT_CFLAGS      : -I$(abs_top_builddir)/third_party/luajit/inc
LUAJIT_LIBS        : $(abs_top_builddir)/third_party/luajit/lib/libluajit-5.1.a -ldl
LUAJIT_LDFLAGS     : -rdynamic

Concurrency Kit    : bundled
CK_CFLAGS          : -I$(abs_top_builddir)/third_party/concurrency_kit/include
CK_LIBS            : $(abs_top_builddir)/third_party/concurrency_kit/lib/libck.a
configure flags    : 
===============================================================================
danielgb@p88:~/sysbench$ 
danielgb@p88:~/sysbench$ make -j
Making all in third_party/luajit
make[1]: Entering directory '/home/danielgb/sysbench/third_party/luajit'
make -C ./luajit clean
make[2]: Entering directory '/home/danielgb/sysbench/third_party/luajit/luajit'
make -C src clean
make[3]: Entering directory '/home/danielgb/sysbench/third_party/luajit/luajit/src'
rm -f luajit libluajit.a libluajit.so host/minilua host/buildvm lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua *.o host/*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
make[3]: Leaving directory '/home/danielgb/sysbench/third_party/luajit/luajit/src'
make[2]: Leaving directory '/home/danielgb/sysbench/third_party/luajit/luajit'
rm -rf tmp
mkdir tmp
tar -C . -cf - luajit | tar -xf - -C tmp/
chmod -R u+w tmp
make -C tmp/luajit \
                PREFIX=/home/danielgb/sysbench/third_party/luajit \
                INSTALL_INC=/home/danielgb/sysbench/third_party/luajit/inc \
                install
make[2]: Entering directory '/home/danielgb/sysbench/third_party/luajit/tmp/luajit'
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[3]: Entering directory '/home/danielgb/sysbench/third_party/luajit/tmp/luajit/src'
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_fold.o
CC        lj_gc.o
CC        lj_obj.o
CC        lj_meta.o
CC        lj_buf.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_str.o
CC        lj_udata.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_api.o
CC        lj_profile.o
CC        lj_vmevent.o
CC        lj_lex.o
CC        lj_strscan.o
CC        lj_bcread.o
CC        lj_opt_mem.o
CC        lj_strfmt.o
CC        lj_bcwrite.o
CC        lj_vmmath.o
CC        lj_ir.o
CC        lj_parse.o
CC        lj_opt_dce.o
CC        lj_opt_loop.o
CC        lj_opt_split.o
CC        lj_load.o
CC        lj_opt_sink.o
CC        lj_opt_narrow.o
CC        lj_strfmt_num.o
CC        lj_mcode.o
CC        lj_char.o
CC        lib_package.o
CC        lj_asm.o
In file included from lj_state.c:26:0:
lj_state.c: In function ‘lua_newstate’:
lj_dispatch.h:108:28: error: ‘GG_State {aka struct GG_State}’ has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^
lj_state.c:227:3: note: in expansion of macro ‘G2J’
   G2J(g)->prngstate = rand();
   ^~~
lj_state.c:238:7: warning: implicit declaration of function ‘LJ_PRNG_BITS’; did you mean ‘LJ_ARCH_BITS’? [-Wimplicit-function-declaration]
   if (LJ_PRNG_BITS(G2J(g), 1)) {
       ^~~~~~~~~~~~
       LJ_ARCH_BITS
CC        lj_trace.o
In file included from lj_state.c:26:0:
lj_dispatch.h:108:28: error: ‘GG_State {aka struct GG_State}’ has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^
lj_state.c:238:20: note: in expansion of macro ‘G2J’
   if (LJ_PRNG_BITS(G2J(g), 1)) {
                    ^~~
CC        lj_snap.o
CC        lj_ccallback.o
CC        lj_ctype.o
lj_dispatch.h:108:28: error: ‘GG_State {aka struct GG_State}’ has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^
</pre>

Obviously found #264 as a trivial enhancement in the mean time. 

If you have time, and since you're a packpack maintainer can I get a hand with the following too please:
https://github.com/packpack/packpack-docker-images/pull/22

**Comment by akopytov** [comment]
OK, I see where the problem is with build errors. My LuaJIT branch has a few patches to improve scalability on many-core ARM64, but that code is missing an `#ifdef LJ_HASJIT`. Will fix shortly.

**Comment by akopytov** [comment]
I tried a number of things, but the brain-damaged PG auth system is killing me. Right now there's something wrong with the ppc64le image too: https://travis-ci.org/akopytov/sysbench/jobs/420418798

I'll take a look at the packpack PR.

**Comment by grooverdan** [comment]
Feel your pain with PG auth system and the inconsistent implementation in travis just making it hard. If you ever try mongodb on Travis its much worse in terms of in-travis image vs installed.

I'll take a look at the ppc64le errors. I can replicate it on hardware outside of travis.

Thanks for merging packpack PR.

**Comment by davidzengxhsh** [comment]
The error is still exist when I compile the master code on a Power9 system:
CC        lib_init.o
CC        luajit.o
In file included from lj_state.c:26:
lj_state.c: In function ‘lua_newstate’:
lj_dispatch.h:108:28: error: ‘GG_State’ {aka ‘struct GG_State’} has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^~
lj_state.c:227:3: note: in expansion of macro ‘G2J’
   G2J(g)->prngstate = rand();
   ^~~
lj_state.c:238:7: warning: implicit declaration of function ‘LJ_PRNG_BITS’; did you mean ‘LJ_ARCH_BITS’? [-Wimplicit-function-declaration]
   if (LJ_PRNG_BITS(G2J(g), 1)) {
       ^~~~~~~~~~~~
       LJ_ARCH_BITS
In file included from lj_state.c:26:
lj_dispatch.h:108:28: error: ‘GG_State’ {aka ‘struct GG_State’} has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^~
lj_state.c:238:20: note: in expansion of macro ‘G2J’
   if (LJ_PRNG_BITS(G2J(g), 1)) {
                    ^~~
lj_dispatch.h:108:28: error: ‘GG_State’ {aka ‘struct GG_State’} has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^~
lj_state.c:243:3: note: in expansion of macro ‘G2J’
   G2J(g)->target = target;
   ^~~
lj_dispatch.h:108:28: error: ‘GG_State’ {aka ‘struct GG_State’} has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^~
lj_state.c:244:3: note: in expansion of macro ‘G2J’
   G2J(g)->range = range;
   ^~~
lj_dispatch.h:108:28: error: ‘GG_State’ {aka ‘struct GG_State’} has no member named ‘J’
 #define G2J(gl)  (&G2GG(gl)->J)
                            ^~
lj_state.c:245:3: note: in expansion of macro ‘G2J’
   G2J(g)->allocbase = allocbase;
   ^~~
make[3]: *** [lj_state.o] Error 1
make[3]: *** Waiting for unfinished jobs....

**Comment by grooverdan** [comment]
travis not happening.

**Pull request closed without merging**
