### PR TITLE
Package RHEL8/FC30

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by akopytov** [comment]
I cannot merge the EL 8 part -- there's no support in packpack and packagecloud, because there is no Centos 8 yet.

I added Fedora 30 in commit 66be0fb.

**Comment by grooverdan** [comment]
Thanks for manually adding FC30.

On RHEL8, not sure what packpack/packagecloud use however maybe [UBI](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) is sufficient.

**Comment by Altiire** [comment]
CentOS 8 was released the 24 septembre, @akopytov can you merge the EL 8 part so sysbench will be available ?

**Comment by akopytov** [comment]
@Altiire Thanks for letting me know. EL8 support has been merged. Packages will be available with the next release.

**Pull request closed without merging**
