### PR TITLE
Fix for parallel_prepare

### PR DESCRIPTION
**Pull request by vadimtk**
with new thread init, parallel_prepare does not work as expected.
moving the logic from _init to event

### CODE REVIEW

**Comment by akopytov** [comment]
Does this really need changes to sysbench.c, or they belong to a different issue?

**Comment by vadimtk** [comment]
This particular change does not require changes to sysbench.c,
it seems github pull request picks up changes made after the pull request.

However the change for sysbench.c is needed to fix tx-rate workload, I was
going to make
another pull request on that.


On Mon, Apr 11, 2016 at 7:27 AM, Alexey Kopytov <notifications@github.com>
wrote:

> Does this really need changes to sysbench.c, or they belong to a different
> issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/akopytov/sysbench/pull/35#issuecomment-208373291>
>



-- 
Vadim Tkachenko, CTO, Percona
Phone +1-919-249-7483,  Skype: vadimtk153

**Comment by akopytov** [comment]
I can merge this proposal as is to simplify things for you. But I would like to understand the tx-rate problem. Can you tell me more about it?

**Comment by vadimtk** [comment]
Alexey,

Sure,

If we force sleep every cycle, I am able to get only max 15000 events/sec
generated in a single generator thread on my box.
If I remove usleep for empty cycles - I am able to get up to 60000
events/sec generated.
Please merge if you can.

Thanks,
Vadim







On Mon, Apr 11, 2016 at 11:25 AM, Alexey Kopytov <notifications@github.com>
wrote:

> I can merge this proposal as is to simplify things for you. But I would
> like to understand the tx-rate problem. Can you tell me more about it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/akopytov/sysbench/pull/35#issuecomment-208486931>
>



-- 
Vadim Tkachenko, CTO, Percona
Phone +1-919-249-7483,  Skype: vadimtk153

**Comment by akopytov** [comment]
Thanks.

**Pull request merged**
