### PR TITLE
use system lua

### PR DESCRIPTION
**Pull request by grooverdan**
lua53 scripts where changed as ints ended up as 34.0 which broke a bunch of sql.

### CODE REVIEW

**Comment by akopytov** [comment]
I'm actually in the process of replacing bundled Lua with bundled LuaJIT (and there are reasons for keeping a bundled copy of LuaJIT). LuaJIT is compatible with Lua 5.1 with a few 5.2/5.3 features backported.

Do you have any specific reasons for using Lua 5.3 with sysbench?

**Comment by grooverdan** [comment]
I was starting to write lua benchmark scripts using the 1e30 numeric syntax which wasn't recognised in 5.1 and then just ported the rest of it.

**Comment by grooverdan** [comment]
Also distros tend to dislike packages included bundled code from a security/quality management point of view.

Perhaps a pkgconfig check for luajit could be added too. I haven't extensively looked at differences in lua implementations.

No reason a option to compile with a bundled luajit couldn't be done either.

**Comment by akopytov** [comment]
Sorry about the delayed response.

I redefined the compile-time constant to make Lua treat numbers as integers on purpose. I know Lua 5.3 added native support for integers. However, LuaJIT uses a hybrid approach when the underlying representation is transparent to applications.

Since I'm migrating to LuaJIT anyway, I'm not sure if I should merge this PR. Would using the luajit branch until it is merged into trunk be a solution for you?

As to bundled vs. system libraries. Yes, packagers would hate me for not having system as an option. OTOH, users would hate me for introducing new external deps. On top of that, LuaJIT is not even available on some popular distributions. And the beta version of LuaJIT has some great performance improvements compared to the latest stable, so I would like to have some flexibility.

**Comment by grooverdan** [comment]
Ok. luajit seems to be quite sane. See you've added a --with-system-luajit. Looks like you can keep everyone happy. Feel free to close. Technically you could add it as a git submodule.

**Comment by akopytov** [comment]
Thanks. Yes, I considered a git submodule, but then again that would require people to add --recursive to git clone. There's no way that I'm aware of to make it a default. So I went with a git subtree instead, it's good enough for my purposes.

**Pull request closed without merging**
