### PR TITLE
Fix db_driver bug: support custormized driver name endswith mysql and pgsql.

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
@akopytov it seems that the existing lines are not covered from last build, I guess tests will cover differently because of some random factors? I'd like to know how to fix the coverage regression. Thanks.

**Comment by akopytov** [comment]
I'm not sure I understand what problem is being solved here. Can you give an example?

**Comment by xunzhang** [comment]
It can support something like this `db_driver=/home/user/local/bin/mysql` if I install mysql or pgsql in customized path.

**Comment by akopytov** [comment]
The drivers are built-in, so they cannot really be moved to another location. That's why I don't see a reason to specify a path instead of a name.

The MySQL/PostgreSQL client libraries are a different story. But they are managed by the dynamic linker, and thus follow the common conventions. I.e. in addition to pre-defined locations, the linker will also look in directories from `LD_LIBRARY_PATH`.  Is this the problem you are solving in the patch?

**Comment by akopytov** [comment]
Closing for now, feel free to comment or reopen if I'm missing something.

**Pull request closed without merging**
