### PR TITLE
Document UUID generation from Lua scripts

### PR DESCRIPTION
**Pull request by jaypipes**
GH Issue #186

Adds support for Linux-native thread-safe UUID generation. A new
sysbench.uuid Lua module is created with a single function
`sysbench.uuid.new()` that returns a string containing a UUID.

### CODE REVIEW

**Comment by akopytov** [comment]
Does libuuid-dev have to be installed in `.travis.yml` to fix Jenkins? Hm, not sure how to fix docker builds though...

**Comment by akopytov** [comment]
After giving it more thought, I think it should better be implemented not in core, but rather as a separate Lua module. The only reason to touch sysbench core here is to provide a libuuid binding for LuaJIT FFI with the downside being an extra build, runtime and package dependencies. 

But that can also be implemented in Lua with help of `ffi.load()`. See, for example, https://github.com/AlexWoo/lua-uuid/blob/master/uuid.lua. Which also provides extra functionality compared to this PR.

I tried using `uuid.lua` from the above link with the following script and got ~2mln UUIDs per core on my laptop:

```lua
local uuid = require("uuid")

function event()
  local uu = uuid:uuid1()
end
```

Would that work for you?

If this becomes a frequently requested feature, I'm happy to package `uuid.lua` as a rock and publish on the sysbench Luarocks repo when it's ready.

**Comment by jaypipes** [comment]
Hi again :) I wasn't aware of AlexWoo's uuid.lua implementation. Looks excellent (since it's thread-safe and clearly performs well). Definitely simpler than adding a compile-time build dep to sysbench.

I will update this Issue/PR to be about documenting how to work with UUIDs in a sysbench Lua script instead of doing the C bindings.

**Comment by jaypipes** [comment]
Closing the PR... will update the Issue.

**Pull request closed without merging**
